"""自定义异常定义"""


class PileNotFoundError(Exception):
    """自定义异常：堆未找到。"""
    pass

